//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.LogDatabase = new HashSet<LogDatabase>();
            this.LogLogin = new HashSet<LogLogin>();
            this.User1 = new HashSet<User>();
            this.User11 = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedIpAddress { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedIpAddress { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CommonUserType CommonUserType { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<LogDatabase> LogDatabase { get; set; }
        public virtual ICollection<LogLogin> LogLogin { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<User> User11 { get; set; }
        public virtual User User3 { get; set; }
    }
}
