//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the Dalyan T4 template.
// Do not change
//
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.Entities.Models
{
    
    using System;
    using System.Collections.Generic;
    
    public partial class CommonUserType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
