//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the Dalyan T4 template.
// Do not change
//
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.Entities.Models
{

    using System;
    using System.Collections.Generic;

    public partial class User
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedIpAddress { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedIpAddress { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public virtual CommonUserType CommonUserType { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual Company Company { get; set; }
    }
}
