//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.Domain.Query
{
    using System;
    using Dalyan.Domain;
    using System.Linq;
    using System.Text;
    using Dalyan.Domain.Query;
    using System.Data;
    using System.Xml;
    using Dalyan.Db;
    using Entities.Models;
    using Dalyan.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;

    public class CompanyGetAllQuery : IQuery<IList<Dalyan.Entities.Models.Company>>
    {

    }

    public class CompanyGetAllQueryHandler : IQueryHandler<CompanyGetAllQuery, IList<Dalyan.Entities.Models.Company>>
    {
        private readonly DbEntities _db;
        public CompanyGetAllQueryHandler()
        {
            _db = new DbEntities();
        }


        public IList<Dalyan.Entities.Models.Company> Handler(CompanyGetAllQuery query)
        {
            try
            {
                var result = _db.Company.Where(x => x.IsDeleted == false).AsEnumerable().ToList();
                Mapper.CreateMap<Dalyan.Db.Company, Dalyan.Entities.Models.Company>();
                return Mapper.Map<IEnumerable<Dalyan.Db.Company>, IEnumerable<Dalyan.Entities.Models.Company>>(result).ToList();

            }
            catch (Exception ex)
            {
                throw new ExceptionLog(LogType.DATABASE_SELECT, LogLevel.ERROR, ex, "GetAllQueryHandler");
            }
        }
    }

}
