//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.Domain.Query
{
    using System;
    using Dalyan.Domain;
    using System.Linq;
    using System.Text;
    using Dalyan.Domain.Query;
    using System.Data;
    using System.Xml;
    using Dalyan.Db;
    using Entities.Models;
    using Dalyan.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;

    public class CompanyRetrieveQuery : IQuery<Dalyan.Entities.Models.Company>
    {
        public int Id { get; set; }
    }

    public class CompanyRetrieveQueryHandler : IQueryHandler<CompanyRetrieveQuery, Dalyan.Entities.Models.Company>
    {
        private readonly DbEntities _db;
        public CompanyRetrieveQueryHandler()
        {
            _db = new DbEntities();
        }


        public Dalyan.Entities.Models.Company Handler(CompanyRetrieveQuery query)
        {
            try
            {
                var result = _db.Company.Where(x => x.IsDeleted == false && x.Id == query.Id).FirstOrDefault();
                Mapper.CreateMap<Dalyan.Db.Company, Dalyan.Entities.Models.Company>();
                return Mapper.Map<Dalyan.Db.Company, Dalyan.Entities.Models.Company>(result);

            }
            catch (Exception ex)
            {
                throw new ExceptionLog(LogType.DATABASE_SELECT, LogLevel.ERROR, ex, "RetrieveQueryHandler");
            }
        }
    }
}
