//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.Domain.Query
{
    using System;
    using Dalyan.Domain;
    using System.Linq;
    using System.Text;
    using Dalyan.Domain.Query;
    using System.Data;
    using System.Xml;
    using Dalyan.Db;
    using Entities.Models;
    using Dalyan.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;

    public class UserGetAllQuery : IQuery<IList<Dalyan.Entities.Models.User>>
    {

    }

    public class UserGetAllQueryHandler : IQueryHandler<UserGetAllQuery, IList<Dalyan.Entities.Models.User>>
    {
        private readonly DbEntities _db;
        public UserGetAllQueryHandler()
        {
            _db = new DbEntities();
        }


        public IList<Dalyan.Entities.Models.User> Handler(UserGetAllQuery query)
        {
            try
            {
                var result = _db.User.Include("CommonUserType").Include("User2").Include("User3").Include("Company").Where(x => x.IsDeleted == false).AsEnumerable().ToList();
                Mapper.CreateMap<Dalyan.Db.CommonUserType, Dalyan.Entities.Models.CommonUserType>();
                Mapper.CreateMap<Dalyan.Db.User, Dalyan.Entities.Models.User>();
                Mapper.CreateMap<Dalyan.Db.Company, Dalyan.Entities.Models.Company>();
                Mapper.CreateMap<Dalyan.Db.User, Dalyan.Entities.Models.User>().ForMember(c => c.CommonUserType, d => d.MapFrom(s => s.CommonUserType)).ForMember(c => c.User2, d => d.MapFrom(s => s.User2)).ForMember(c => c.User3, d => d.MapFrom(s => s.User3)).ForMember(c => c.Company, d => d.MapFrom(s => s.Company));
                return Mapper.Map<IEnumerable<Dalyan.Db.User>, IEnumerable<Dalyan.Entities.Models.User>>(result).ToList();

            }
            catch (Exception ex)
            {
                throw new ExceptionLog(LogType.DATABASE_SELECT, LogLevel.ERROR, ex, "GetAllQueryHandler");
            }
        }
    }

}
