//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.Domain.Query
{
    using System;
    using Dalyan.Domain;
    using System.Linq;
    using System.Text;
    using Dalyan.Domain.Query;
    using System.Data;
    using System.Xml;
    using Dalyan.Db;
    using Entities.Models;
    using Dalyan.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;

    public class UserDeleteQuery : IQuery<bool>
    {
        public int Id { get; set; }
    }

    public class UserDeleteQueryHandler : IQueryHandler<Dalyan.Domain.Query.UserDeleteQuery, bool>
    {
        private readonly DbEntities _db;
        public UserDeleteQueryHandler()
        {
            _db = new DbEntities();
        }


        public bool Handler(Dalyan.Domain.Query.UserDeleteQuery query)
        {
            try
            {
                var obj = new Dalyan.Db.User();
                obj = _db.User.FirstOrDefault(x => x.Id == query.Id);

                obj.IsDeleted = true;
                _db.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {
                throw new ExceptionLog(LogType.DATABASE_DELETE, LogLevel.ERROR, ex, "DeleteQueryHandler");
            }
        }
    }

}
