//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.WebApi.Controllers
{
    using System;
    using SimpleInjector;
    using Dalyan.Entities;
    using System.Linq;
    using System.Net;
    using System.Web.Http;
    using System.Net.Http;
    using Dalyan.Entities.Models;
    using Dalyan.Service;
    using Entities.Contracts;
    using Dalyan.WebApi.Attributes;
    using Dalyan.Service.Services;
    using System.Collections.Generic;
    
    public class SampleTableController : ApiController
    {
    	private readonly Container _container;
    	public SampleTableController(Container container)
     		: base()
    	{
    		_container = container;
    	}
    
    	    
    	[UserAuthorize]
    	[HttpPost]
    	public ServiceResult<SampleTable> Add(SampleTable obj)
    	{
    		SampleTableService service = new SampleTableService(_container);
    		return service.Add(obj);
    	}
    	[UserAuthorize]
    	[HttpPost]
    	public ServiceResult<SampleTable> Edit(SampleTable obj)
    	{
    		SampleTableService service = new SampleTableService(_container);
    		return service.Edit(obj);
    	}
    	[UserAuthorize]
    	[HttpPost]
    	public ServiceResult<SampleTable> Retrieve(int Id)
    	{
    		SampleTableService service = new SampleTableService(_container);
    		return service.Retrieve(Id);
    	}
    	[UserAuthorize]
    	[HttpPost]
    	public ServiceResult<IList<SampleTable>> GetAll()
    	{
    		SampleTableService service = new SampleTableService(_container);
    		return service.GetAll();
    	}
    	[UserAuthorize]
    	[HttpPost]
    	public ServiceResult<string> Delete(int Id)
    	{
    		SampleTableService service = new SampleTableService(_container);
    		return service.Delete(Id);
    	}
    }
}
