//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.Service.Services
{
    using System;
    using SimpleInjector;
    using Dalyan.Domain;
    using System.Linq;
    using System.Text;
    using Dalyan.Domain.Query;
    using System.Data;
    using System.Xml;
    using Dalyan.Entities.Models;
    using Dalyan.Entities.Enumerations;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    using Entities.Interfaces;
    using Entities.Contracts;

    public class UserService
    {
        private readonly Container _container;
        public UserService(Container container)
        {
            _container = container;
        }


        public ServiceResult<User> Add(User obj)
        {
            try
            {
                IMediator service = _container.GetInstance<IMediator>();
                IUserContext currentUser = _container.GetInstance<IUserContext>();
                var query = new UserAddQuery();
                obj.CreatedDate = DateTime.Now;
                obj.CreatedUserId = currentUser.CurrentUserIdentity.UserID;
                obj.CreatedIpAddress = currentUser.CurrentUserIdentity.IpAddress;
                obj.UpdatedDate = DateTime.Now;
                obj.UpdatedUserId = currentUser.CurrentUserIdentity.UserID;
                obj.UpdatedIpAddress = currentUser.CurrentUserIdentity.IpAddress;
                query.User = obj;
                return new ServiceResult<User>(service.Proccess(query), message: ClientErrorMessage.Success(), state: ServiceResultStates.SUCCESS);
            }
            catch (ExceptionLog ex)
            {
                LoggerService.Logger.Log(_container, ex);
                return new ServiceResult<User>(result: null, message: ClientErrorMessage.Error(), state: ServiceResultStates.ERROR);
            }
        }
        public ServiceResult<User> Edit(User obj)
        {
            try
            {
                IMediator service = _container.GetInstance<IMediator>();
                var query = new UserEditQuery();
                query.User = obj;
                return new ServiceResult<User>(service.Proccess(query), message: ClientErrorMessage.Success(), state: ServiceResultStates.SUCCESS);
            }
            catch (ExceptionLog ex)
            {
                LoggerService.Logger.Log(_container, ex);
                return new ServiceResult<User>(result: null, message: ClientErrorMessage.Error(), state: ServiceResultStates.ERROR);
            }
        }
        public ServiceResult<User> Retrieve(int Id)
        {
            try
            {
                IMediator service = _container.GetInstance<IMediator>();
                var query = new UserRetrieveQuery { Id = Id };
                return new ServiceResult<User>(service.Proccess(query), message: ClientErrorMessage.Success(), state: ServiceResultStates.SUCCESS);
            }
            catch (ExceptionLog ex)
            {
                LoggerService.Logger.Log(_container, ex);
                return new ServiceResult<User>(result: null, message: ClientErrorMessage.Error(), state: ServiceResultStates.ERROR);
            }
        }
        public ServiceResult<IList<User>> GetAll()
        {
            try
            {
                IMediator service = _container.GetInstance<IMediator>();
                var query = new UserGetAllQuery();
                return new ServiceResult<IList<User>>(service.Proccess(query), message: ClientErrorMessage.Success(), state: ServiceResultStates.SUCCESS);
            }
            catch (ExceptionLog ex)
            {
                LoggerService.Logger.Log(_container, ex);
                return new ServiceResult<IList<User>>(result: null, message: ClientErrorMessage.Error(), state: ServiceResultStates.ERROR);
            }
        }
        public ServiceResult<string> Delete(int Id)
        {
            try
            {
                IMediator service = _container.GetInstance<IMediator>();
                var query = new UserDeleteQuery { Id = Id };
                return new ServiceResult<string>(service.Proccess(query).ToString(), message: ClientErrorMessage.Success(), state: ServiceResultStates.SUCCESS);
            }
            catch (ExceptionLog ex)
            {
                LoggerService.Logger.Log(_container, ex);
                return new ServiceResult<string>(result: "false", message: ClientErrorMessage.Error(), state: ServiceResultStates.ERROR);
            }
        }
    }
}
