//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.Domain.Query
{
    using System;
    using Dalyan.Domain;
    using System.Linq;
    using System.Text;
    using Dalyan.Domain.Query;
    using System.Data;
    using System.Xml;
    using Dalyan.Db;
    using Entities.Models;
    using Dalyan.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    
    public class SampleTableGetAllQuery : IQuery<IList<Dalyan.Entities.Models.SampleTable>>
    {
    	
    }
    
    public class SampleTableGetAllQueryHandler : IQueryHandler<SampleTableGetAllQuery, IList<Dalyan.Entities.Models.SampleTable>>
    {
    	private readonly DbEntities _db;
    	public SampleTableGetAllQueryHandler()
    	{
    		_db = new DbEntities();
    	}
    
    	    
    	public IList<Dalyan.Entities.Models.SampleTable> Handler(SampleTableGetAllQuery query)
    	{
    		try
    		{
    			var result = _db.SampleTable.Include("Company").Where(x => x.IsDeleted == false).AsEnumerable().ToList();
    			Mapper.CreateMap<Dalyan.Db.Company, Dalyan.Entities.Models.Company>();
    			Mapper.CreateMap<Dalyan.Db.SampleTable, Dalyan.Entities.Models.SampleTable>().ForMember(c => c.Company, d => d.MapFrom(s => s.Company));
    			return Mapper.Map<IEnumerable<Dalyan.Db.SampleTable>, IEnumerable<Dalyan.Entities.Models.SampleTable>>(result).ToList();
    
    		}
    		catch (Exception ex)
    		{
    			throw new ExceptionLog(LogType.DATABASE_SELECT, LogLevel.ERROR, ex, "GetAllQueryHandler");
    		}
    	}
    }
    
}
