//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalyan.Domain.Query
{
    using System;
    using Dalyan.Domain;
    using System.Linq;
    using System.Text;
    using Dalyan.Domain.Query;
    using System.Data;
    using System.Xml;
    using Dalyan.Db;
    using Entities.Models;
    using Dalyan.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    
    public class SampleTableAddQuery : IQuery<Dalyan.Entities.Models.SampleTable>
    {
    	public Dalyan.Entities.Models.SampleTable SampleTable{ get; set; }
    }
    
    public class SampleTableAddQueryHandler : IQueryHandler<SampleTableAddQuery,Dalyan.Entities.Models.SampleTable>
    {
    	private readonly DbEntities _db;
    	public SampleTableAddQueryHandler()
    	{
    		_db = new DbEntities();
    	}
    
    	    
    	public Dalyan.Entities.Models.SampleTable Handler(SampleTableAddQuery query)
    	{
    		try
    		{
    			var obj = new Dalyan.Db.SampleTable();
    			obj.Id = query.SampleTable.Id;
    			obj.Name = query.SampleTable.Name;
    			obj.CompanyId = query.SampleTable.CompanyId;
    			obj.Gender = query.SampleTable.Gender;
    			obj.Active = query.SampleTable.Active;
    			obj.Movies = query.SampleTable.Movies;
    			obj.Series = query.SampleTable.Series;
    			obj.ProfilePicture = query.SampleTable.ProfilePicture;
    			obj.LoginDate = query.SampleTable.LoginDate;
    			obj.LongLoginDate = query.SampleTable.LongLoginDate;
    			obj.LongText = query.SampleTable.LongText;
    			obj.Price = query.SampleTable.Price;
    			obj.Price2 = query.SampleTable.Price2;
    			obj.CreatedDate = query.SampleTable.CreatedDate;
    			obj.CreatedIpAddress = query.SampleTable.CreatedIpAddress;
    			obj.CreatedUserId = query.SampleTable.CreatedUserId;
    			obj.UpdatedDate = query.SampleTable.UpdatedDate;
    			obj.UpdatedIpAddress = query.SampleTable.UpdatedIpAddress;
    			obj.UpdatedUserId = query.SampleTable.UpdatedUserId;
    			obj.IsDeleted = query.SampleTable.IsDeleted;
    			_db.SampleTable.Add(obj);
    			_db.SaveChanges();
    			query.SampleTable.Id = obj.Id;
    			return query.SampleTable;
    
    		}
    		catch (Exception ex)
    		{
    			throw new ExceptionLog(LogType.DATABASE_INSERT, LogLevel.ERROR, ex, "AddQueryHandler");
    		}
    	}
    }
    
    
}
